### ISSUE TITLE
Module Failure while executing in Ansible 2.9

### ISSUE THREAD

**Issue by TUDAYALAKSHMI** [fortinet-solutions-cse/ansible_fgt_modules#22]
I am using below modules:
fortios_firewall_addrgrp
fortios_firewall_schedule_group
fortios_firewall_service_group
fortios-firewall-vipgrp
fortios-firewall-wildcard-fqdn-group
fortios_router_static

Those are working in Ansible(2.8), but giving below error in Ansible(2.9)

TASK [Configure service groups.] ***************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: login() got an unexpected keyword argument 'verify'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n File \"/root/.ansible/tmp/ansible-tmp-1573801410.99-124280751610118/AnsiballZ_fortios_firewall_service_group.py\", line 102, in <module>\n ansiballz_main()\n File \"/root/.ansible/tmp/ansible-tmp-1573801410.99-124280751610118/AnsiballZ_fortios_firewall_service_group.py\", line 94, in ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/root/.ansible/tmp/ansible-tmp-1573801410.99-124280751610118/AnsiballZ_fortios_firewall_service_group.py\", line 40, in invoke_module\n runpy.run_module(mod_name='ansible.modules.network.fortios.fortios_firewall_service_group', init_globals=None, run_name='__main__', alter_sys=False)\n File \"/usr/lib64/python2.7/runpy.py\", line 180, in run_module\n fname, loader, pkg_name)\n File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n exec code in run_globals\n File \"/tmp/ansible_fortios_firewall_service_group_payload_GRV2XN/ansible_fortios_firewall_service_group_payload.zip/ansible/modules/network/fortios/fortios_firewall_service_group.py\", line 371, in <module>\n File \"/tmp/ansible_fortios_firewall_service_group_payload_GRV2XN/ansible_fortios_firewall_service_group_payload.zip/ansible/modules/network/fortios/fortios_firewall_service_group.py\", line 360, in main\n File \"/tmp/ansible_fortios_firewall_service_group_payload_GRV2XN/ansible_fortios_firewall_service_group_payload.zip/ansible/modules/network/fortios/fortios_firewall_service_group.py\", line 240, in login\nTypeError: login() got an unexpected keyword argument 'verify'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

My playbook is:
---
- hosts: localhost
vars:
host: "X.X.X.X"
username: "XXX"
password: "XXXX"
vdom: "root"
ssl_verify: "False"
tasks:
- name: Configure IPv4 address groups.
fortios_firewall_addrgrp:
host: "{{ host }}"
username: "{{ username }}"
password: "{{ password }}"
vdom: "{{ vdom }}"
https: "False"
state: "present"
firewall_addrgrp:
allow_routing: "enable"
color: "4"
comment: "Comment."
member:
- name: "ASA"
name: "Netenrich"
visibility: "enable"

Thanks in advance

**Comment by chillancezen** [comment]
triaging...

**Comment by chillancezen** [comment]
hi, 
I can not reproduce your issue on my own:
my Ansible version:
```
#ansible-playbook --version
ansible-playbook 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/BUGTRIAGE/ansible_fgt_modules_issue_22/env/lib/python3.6/site-packages/ansible
  executable location = /root/BUGTRIAGE/ansible_fgt_modules_issue_22/env/bin/ansible-playbook
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

my playbook:
```
#cat test.yml
- hosts: localhost
  vars:
   host: "172.22.13.10"
   username: "admin"
   password: "ca$hc0w"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure VPN remote gateway.
    fortios_firewall_addrgrp:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      state: "present"
      ssl_verify: "False"
      firewall_addrgrp:
        color: '4'
        comment: 'no comment'
        name: 'Foo_remote'
```

result:
```
#ansible-playbook  test.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Configure VPN remote gateway.] *********************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

my DUT:
```
FGVM04TM19006963 # get  system status
Version: FortiGate-VM64 v6.4.0,build1509,191106 (interim)
Virus-DB: 1.00000(2018-04-09 18:07)
Extended DB: 1.00000(2018-04-09 18:07)
Extreme DB: 1.00000(2018-04-09 18:07)
IPS-DB: 6.00741(2015-12-01 02:30)
IPS-ETDB: 6.00741(2015-12-01 02:30)
APP-DB: 6.00741(2015-12-01 02:30)
INDUSTRIAL-DB: 6.00741(2015-12-01 02:30)
Serial-Number: FGVM04TM19006963
IPS Malicious URL Database: 1.00001(2015-01-01 01:01)
Botnet DB: 1.00000(2012-05-28 22:51)
License Status: Valid
License Expires: 2020-10-24
VM Resources: 1 CPU/4 allowed, 1002 MB RAM
Log hard disk: Available
Hostname: FGVM04TM19006963
Operation Mode: NAT
Current virtual domain: root
Max number of virtual domains: 10
Virtual domains status: 1 in NAT mode, 0 in TP mode
Virtual domain configuration: disable
FIPS-CC mode: disable
Current HA mode: standalone
Branch point: 1509
Release Version Information: interim
FortiOS x86-64: Yes
System time: Mon Dec 23 01:25:55 2019
```

could you share us more the your env?

thanks,
Link

**Comment by chillancezen** [comment]
@TUDAYALAKSHMI TUDAYALAKSHMI

**Comment by razikhussein** [comment]
Is there a solution found for this?
I'm using Ansible 2.9.2 and fortiosapi 0.9.8,, on python3.6, and getting the same error

**Comment by mamunozgonzalez** [comment]
Hi,
this repository is deprecated already and development has been moved to collections:

https://galaxy.ansible.com/fortinet/fortios

Anyway, as a suggestion, please use HTTPAPI connectivity instead of localhost (fortiosapi).
fortiosapi is for localhost only and is deprecated in Ansible.

Here you can find an example on how to use HTTPAPI (remember that you have to define an inventory):

https://github.com/fortinet-solutions-cse/ansible_fgt_modules/tree/master/example_with_httpapi
https://github.com/fortinet-solutions-cse/ansible_fgt_modules/tree/master/hosts
